Work ongoing with wait for service

diff --git a/eiffel-gerrit-plugin-script b/eiffel-gerrit-plugin-script
--- a/eiffel-gerrit-plugin-script
+++ b/eiffel-gerrit-plugin-script
@@ -72,27 +72,7 @@ function do_start {
   RABBITMQ_BASE_URL=http://$RABBITMQ_API_HOST:15672
   GERRIT_BASE_URL=http://$GERRIT_API_HOST:8080
 
-  rabbitmq_attempt_counter=0
-  rabbitmq_max_attempts=60
-
-  printf "WAITING FOR RABBITMQ TO START WITH URL: "$RABBITMQ_BASE_URL
-  echo " "
-  until $(curl --output /dev/null --silent --head --fail $RABBITMQ_BASE_URL); do
-      if [ ${rabbitmq_attempt_counter} -eq ${rabbitmq_max_attempts} ];then
-        printf " \e[91m FAILURE! \e[39m"
-        echo " "
-        echo "RabbitMQ failed to start!"
-        do_stop
-        exit 1
-      fi
-
-      printf '.'
-      rabbitmq_attempt_counter=$(($rabbitmq_attempt_counter+1))
-      sleep 2
-  done
-
-  printf " \e[32m SUCCESS! \e[39m"
-  echo " "
+  wait_for_service "$RABBITMQ_BASE_URL" "RABBITMQ"
   
   printf "WAITING FOR GERRIT TO START WITH URL: "$GERRIT_BASE_URL
   echo " "
@@ -145,6 +125,34 @@ function do_full_test {
   do_start
   do_test
   do_stop
+}
+
+function wait_for_service {
+  base_url="$1"
+  service_name="$2"
+  echo "the url is ${base_url}"
+  
+  attempt_counter=0
+  max_attempts=60
+  
+  printf "WAITING FOR $service_name TO START WITH URL: "${base_url}
+  echo " "
+  until $(curl --output /dev/null --silent --head --fail ${base_url}); do
+      if [ ${attempt_counter} -eq ${max_attempts} ];then
+        printf " \e[91m FAILURE! \e[39m"
+        echo " "
+        echo "RabbitMQ failed to start!"
+        do_stop
+        exit 1
+      fi
+
+      printf '.'
+      attempt_counter=$(($attempt_counter+1))
+      sleep 2
+  done
+
+  printf " \e[32m SUCCESS! \e[39m"
+  echo " "
 }
 
 unamestr=`uname`
