Fix changes

diff --git a/eiffel-gerrit-plugin-script b/eiffel-gerrit-plugin-script
--- a/eiffel-gerrit-plugin-script
+++ b/eiffel-gerrit-plugin-script
@@ -1,7 +1,6 @@
 #! /bin/bash
 
 GERRIT_API_HOST=""
-RABBITMQ_API_HOST=""
 STATUS=0
 
 function invalid_arguments {
@@ -27,9 +26,13 @@ function invalid_arguments {
 
 function do_stop {
   echo "########################################"
-  echo "###### STOPING DOCKER SERVICES #########"
+  echo "###### STOPPING DOCKER SERVICES ########"
   echo "########################################"
   docker-compose -f target/docker-compose.yml down
+  if [ $? -eq 1 ]; then
+    echo "Failed to stop docker containers!"
+    exit 1  
+  fi
 }
 
 function do_rebuild {
@@ -43,6 +46,10 @@ function do_rebuild {
   mv target/test-classes/Dockerfile target/Dockerfile
 
   docker build -f target/Dockerfile -t plugin-test target/
+  if [ $? -eq 1 ]; then
+    echo "Failed to build docker file!"
+    exit 1  
+  fi 
 }
 
 function do_start {
@@ -67,7 +74,7 @@ function do_start {
       if [ ${attempt_counter} -eq ${max_attempts} ];then
         printf " \e[91m FAILURE! \e[39m"
         echo " "
-        echo "Gerrit failed to start aborting!"
+        echo "Gerrit failed to start!"
         do_stop
         exit 1
       fi
@@ -89,7 +96,7 @@ function do_test {
   GERRIT_API_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $GERRIT_CONTAINER_ID)
 
   # Installing firefox binary before integration tests
-  mvn exec:exec
+  # mvn exec:exec
   mvn verify -DskipUTs -Dgerrit.url=$GERRIT_API_HOST
   STATUS=$?
 }
@@ -109,6 +116,12 @@ function do_full_test {
   do_test
   do_stop
 }
+
+unamestr=`uname`
+if [ "$unamestr" != "Linux" ]; then
+   echo "Unsupported operating system, this script currently only works in Linux!"
+   exit 1
+fi
 
 if [ $# -eq 0 ]; then
   invalid_arguments
